/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedVehiclesImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedTripsImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedShipmentsImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSetupImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedRoutesImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as unauthenticatedLoginImport } from './routes/(unauthenticated)/login'
import { Route as AuthenticatedVehiclesIndexImport } from './routes/_authenticated/vehicles/index'
import { Route as AuthenticatedTripsIndexImport } from './routes/_authenticated/trips/index'
import { Route as AuthenticatedShipmentsIndexImport } from './routes/_authenticated/shipments/index'
import { Route as AuthenticatedRoutesIndexImport } from './routes/_authenticated/routes/index'
import { Route as AuthenticatedVehiclesAddImport } from './routes/_authenticated/vehicles/add'
import { Route as AuthenticatedVehiclesIdImport } from './routes/_authenticated/vehicles/$id'
import { Route as AuthenticatedTripsNewImport } from './routes/_authenticated/trips/new'
import { Route as AuthenticatedTripsIdImport } from './routes/_authenticated/trips/$id'
import { Route as AuthenticatedStationsAddImport } from './routes/_authenticated/stations/add'
import { Route as AuthenticatedStaffAddImport } from './routes/_authenticated/staff/add'
import { Route as AuthenticatedShipmentsNewImport } from './routes/_authenticated/shipments/new'
import { Route as AuthenticatedShipmentsIdImport } from './routes/_authenticated/shipments/$id'
import { Route as AuthenticatedSetupItemTypesImport } from './routes/_authenticated/setup/item-types'
import { Route as AuthenticatedSetupItemCategoriesImport } from './routes/_authenticated/setup/item-categories'
import { Route as AuthenticatedSetupConfigImport } from './routes/_authenticated/setup/config'
import { Route as AuthenticatedSetupAdditionalChargesImport } from './routes/_authenticated/setup/additional-charges'
import { Route as AuthenticatedRoutesAddImport } from './routes/_authenticated/routes/add'
import { Route as AuthenticatedRoutesIdImport } from './routes/_authenticated/routes/$id'
import { Route as AuthenticatedOrdersNewImport } from './routes/_authenticated/orders/new'
import { Route as AuthenticatedOrdersIdImport } from './routes/_authenticated/orders/$id'
import { Route as AuthenticatedCustomersAddImport } from './routes/_authenticated/customers/add'
import { Route as AuthenticatedUserSecurityIndexImport } from './routes/_authenticated/user/security/index'
import { Route as AuthenticatedTripsIdIndexImport } from './routes/_authenticated/trips/$id/index'
import { Route as AuthenticatedOrdersIdIndexImport } from './routes/_authenticated/orders/$id/index'
import { Route as AuthenticatedTripsIdEditImport } from './routes/_authenticated/trips/$id/edit'
import { Route as AuthenticatedOrdersIdSummaryImport } from './routes/_authenticated/orders/$id/summary'
import { Route as AuthenticatedOrdersIdPaymentImport } from './routes/_authenticated/orders/$id/payment'
import { Route as AuthenticatedCustomersCorporateAddImport } from './routes/_authenticated/customers/corporate/add'
import { Route as AuthenticatedCustomersCorporateIdImport } from './routes/_authenticated/customers/corporate/$id'
import { Route as AuthenticatedCustomersCorporateIdIndexImport } from './routes/_authenticated/customers/corporate/$id/index'
import { Route as AuthenticatedUserSecurityFormsPinFormImport } from './routes/_authenticated/user/security/_forms/_pin-form'
import { Route as AuthenticatedUserSecurityFormsPasswordFormImport } from './routes/_authenticated/user/security/_forms/_password-form'
import { Route as AuthenticatedCustomersCorporateIdRefillImport } from './routes/_authenticated/customers/corporate/$id/refill'

// Create Virtual Routes

const AuthenticatedUserSecurityFormsImport = createFileRoute(
  '/_authenticated/user/security/_forms',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVehiclesRoute = AuthenticatedVehiclesImport.update({
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedTripsRoute = AuthenticatedTripsImport.update({
  path: '/trips',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedShipmentsRoute = AuthenticatedShipmentsImport.update({
  path: '/shipments',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSetupRoute = AuthenticatedSetupImport.update({
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRoutesRoute = AuthenticatedRoutesImport.update({
  path: '/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const unauthenticatedLoginRoute = unauthenticatedLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVehiclesIndexRoute = AuthenticatedVehiclesIndexImport.update(
  {
    path: '/',
    getParentRoute: () => AuthenticatedVehiclesRoute,
  } as any,
)

const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)

const AuthenticatedShipmentsIndexRoute =
  AuthenticatedShipmentsIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedShipmentsRoute,
  } as any)

const AuthenticatedRoutesIndexRoute = AuthenticatedRoutesIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)

const AuthenticatedVehiclesAddRoute = AuthenticatedVehiclesAddImport.update({
  path: '/add',
  getParentRoute: () => AuthenticatedVehiclesRoute,
} as any)

const AuthenticatedVehiclesIdRoute = AuthenticatedVehiclesIdImport.update({
  path: '/$id',
  getParentRoute: () => AuthenticatedVehiclesRoute,
} as any)

const AuthenticatedTripsNewRoute = AuthenticatedTripsNewImport.update({
  path: '/new',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)

const AuthenticatedTripsIdRoute = AuthenticatedTripsIdImport.update({
  path: '/$id',
  getParentRoute: () => AuthenticatedTripsRoute,
} as any)

const AuthenticatedStationsAddRoute = AuthenticatedStationsAddImport.update({
  path: '/stations/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedStaffAddRoute = AuthenticatedStaffAddImport.update({
  path: '/staff/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedShipmentsNewRoute = AuthenticatedShipmentsNewImport.update({
  path: '/new',
  getParentRoute: () => AuthenticatedShipmentsRoute,
} as any)

const AuthenticatedShipmentsIdRoute = AuthenticatedShipmentsIdImport.update({
  path: '/$id',
  getParentRoute: () => AuthenticatedShipmentsRoute,
} as any)

const AuthenticatedSetupItemTypesRoute =
  AuthenticatedSetupItemTypesImport.update({
    path: '/item-types',
    getParentRoute: () => AuthenticatedSetupRoute,
  } as any)

const AuthenticatedSetupItemCategoriesRoute =
  AuthenticatedSetupItemCategoriesImport.update({
    path: '/item-categories',
    getParentRoute: () => AuthenticatedSetupRoute,
  } as any)

const AuthenticatedSetupConfigRoute = AuthenticatedSetupConfigImport.update({
  path: '/config',
  getParentRoute: () => AuthenticatedSetupRoute,
} as any)

const AuthenticatedSetupAdditionalChargesRoute =
  AuthenticatedSetupAdditionalChargesImport.update({
    path: '/additional-charges',
    getParentRoute: () => AuthenticatedSetupRoute,
  } as any)

const AuthenticatedRoutesAddRoute = AuthenticatedRoutesAddImport.update({
  path: '/add',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)

const AuthenticatedRoutesIdRoute = AuthenticatedRoutesIdImport.update({
  path: '/$id',
  getParentRoute: () => AuthenticatedRoutesRoute,
} as any)

const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewImport.update({
  path: '/orders/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdImport.update({
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCustomersAddRoute = AuthenticatedCustomersAddImport.update({
  path: '/customers/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUserSecurityFormsRoute =
  AuthenticatedUserSecurityFormsImport.update({
    id: '/user/security/_forms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedUserSecurityIndexRoute =
  AuthenticatedUserSecurityIndexImport.update({
    path: '/user/security/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTripsIdIndexRoute = AuthenticatedTripsIdIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedTripsIdRoute,
} as any)

const AuthenticatedOrdersIdIndexRoute = AuthenticatedOrdersIdIndexImport.update(
  {
    path: '/',
    getParentRoute: () => AuthenticatedOrdersIdRoute,
  } as any,
)

const AuthenticatedTripsIdEditRoute = AuthenticatedTripsIdEditImport.update({
  path: '/edit',
  getParentRoute: () => AuthenticatedTripsIdRoute,
} as any)

const AuthenticatedOrdersIdSummaryRoute =
  AuthenticatedOrdersIdSummaryImport.update({
    path: '/summary',
    getParentRoute: () => AuthenticatedOrdersIdRoute,
  } as any)

const AuthenticatedOrdersIdPaymentRoute =
  AuthenticatedOrdersIdPaymentImport.update({
    path: '/payment',
    getParentRoute: () => AuthenticatedOrdersIdRoute,
  } as any)

const AuthenticatedCustomersCorporateAddRoute =
  AuthenticatedCustomersCorporateAddImport.update({
    path: '/customers/corporate/add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCustomersCorporateIdRoute =
  AuthenticatedCustomersCorporateIdImport.update({
    path: '/customers/corporate/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedCustomersCorporateIdIndexRoute =
  AuthenticatedCustomersCorporateIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedCustomersCorporateIdRoute,
  } as any)

const AuthenticatedUserSecurityFormsPinFormRoute =
  AuthenticatedUserSecurityFormsPinFormImport.update({
    id: '/_pin-form',
    getParentRoute: () => AuthenticatedUserSecurityFormsRoute,
  } as any)

const AuthenticatedUserSecurityFormsPasswordFormRoute =
  AuthenticatedUserSecurityFormsPasswordFormImport.update({
    id: '/_password-form',
    getParentRoute: () => AuthenticatedUserSecurityFormsRoute,
  } as any)

const AuthenticatedCustomersCorporateIdRefillRoute =
  AuthenticatedCustomersCorporateIdRefillImport.update({
    path: '/refill',
    getParentRoute: () => AuthenticatedCustomersCorporateIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(unauthenticated)/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedLoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/customers/add': {
      id: '/_authenticated/customers/add'
      path: '/customers/add'
      fullPath: '/customers/add'
      preLoaderRoute: typeof AuthenticatedCustomersAddImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/routes/$id': {
      id: '/_authenticated/routes/$id'
      path: '/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof AuthenticatedRoutesIdImport
      parentRoute: typeof AuthenticatedRoutesImport
    }
    '/_authenticated/routes/add': {
      id: '/_authenticated/routes/add'
      path: '/add'
      fullPath: '/routes/add'
      preLoaderRoute: typeof AuthenticatedRoutesAddImport
      parentRoute: typeof AuthenticatedRoutesImport
    }
    '/_authenticated/setup/additional-charges': {
      id: '/_authenticated/setup/additional-charges'
      path: '/additional-charges'
      fullPath: '/setup/additional-charges'
      preLoaderRoute: typeof AuthenticatedSetupAdditionalChargesImport
      parentRoute: typeof AuthenticatedSetupImport
    }
    '/_authenticated/setup/config': {
      id: '/_authenticated/setup/config'
      path: '/config'
      fullPath: '/setup/config'
      preLoaderRoute: typeof AuthenticatedSetupConfigImport
      parentRoute: typeof AuthenticatedSetupImport
    }
    '/_authenticated/setup/item-categories': {
      id: '/_authenticated/setup/item-categories'
      path: '/item-categories'
      fullPath: '/setup/item-categories'
      preLoaderRoute: typeof AuthenticatedSetupItemCategoriesImport
      parentRoute: typeof AuthenticatedSetupImport
    }
    '/_authenticated/setup/item-types': {
      id: '/_authenticated/setup/item-types'
      path: '/item-types'
      fullPath: '/setup/item-types'
      preLoaderRoute: typeof AuthenticatedSetupItemTypesImport
      parentRoute: typeof AuthenticatedSetupImport
    }
    '/_authenticated/shipments/$id': {
      id: '/_authenticated/shipments/$id'
      path: '/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof AuthenticatedShipmentsIdImport
      parentRoute: typeof AuthenticatedShipmentsImport
    }
    '/_authenticated/shipments/new': {
      id: '/_authenticated/shipments/new'
      path: '/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof AuthenticatedShipmentsNewImport
      parentRoute: typeof AuthenticatedShipmentsImport
    }
    '/_authenticated/staff/add': {
      id: '/_authenticated/staff/add'
      path: '/staff/add'
      fullPath: '/staff/add'
      preLoaderRoute: typeof AuthenticatedStaffAddImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/stations/add': {
      id: '/_authenticated/stations/add'
      path: '/stations/add'
      fullPath: '/stations/add'
      preLoaderRoute: typeof AuthenticatedStationsAddImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/trips/$id': {
      id: '/_authenticated/trips/$id'
      path: '/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AuthenticatedTripsIdImport
      parentRoute: typeof AuthenticatedTripsImport
    }
    '/_authenticated/trips/new': {
      id: '/_authenticated/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthenticatedTripsNewImport
      parentRoute: typeof AuthenticatedTripsImport
    }
    '/_authenticated/vehicles/$id': {
      id: '/_authenticated/vehicles/$id'
      path: '/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof AuthenticatedVehiclesIdImport
      parentRoute: typeof AuthenticatedVehiclesImport
    }
    '/_authenticated/vehicles/add': {
      id: '/_authenticated/vehicles/add'
      path: '/add'
      fullPath: '/vehicles/add'
      preLoaderRoute: typeof AuthenticatedVehiclesAddImport
      parentRoute: typeof AuthenticatedVehiclesImport
    }
    '/_authenticated/routes/': {
      id: '/_authenticated/routes/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexImport
      parentRoute: typeof AuthenticatedRoutesImport
    }
    '/_authenticated/shipments/': {
      id: '/_authenticated/shipments/'
      path: '/'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AuthenticatedShipmentsIndexImport
      parentRoute: typeof AuthenticatedShipmentsImport
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexImport
      parentRoute: typeof AuthenticatedTripsImport
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexImport
      parentRoute: typeof AuthenticatedVehiclesImport
    }
    '/_authenticated/customers/corporate/$id': {
      id: '/_authenticated/customers/corporate/$id'
      path: '/customers/corporate/$id'
      fullPath: '/customers/corporate/$id'
      preLoaderRoute: typeof AuthenticatedCustomersCorporateIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/customers/corporate/add': {
      id: '/_authenticated/customers/corporate/add'
      path: '/customers/corporate/add'
      fullPath: '/customers/corporate/add'
      preLoaderRoute: typeof AuthenticatedCustomersCorporateAddImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/orders/$id/payment': {
      id: '/_authenticated/orders/$id/payment'
      path: '/payment'
      fullPath: '/orders/$id/payment'
      preLoaderRoute: typeof AuthenticatedOrdersIdPaymentImport
      parentRoute: typeof AuthenticatedOrdersIdImport
    }
    '/_authenticated/orders/$id/summary': {
      id: '/_authenticated/orders/$id/summary'
      path: '/summary'
      fullPath: '/orders/$id/summary'
      preLoaderRoute: typeof AuthenticatedOrdersIdSummaryImport
      parentRoute: typeof AuthenticatedOrdersIdImport
    }
    '/_authenticated/trips/$id/edit': {
      id: '/_authenticated/trips/$id/edit'
      path: '/edit'
      fullPath: '/trips/$id/edit'
      preLoaderRoute: typeof AuthenticatedTripsIdEditImport
      parentRoute: typeof AuthenticatedTripsIdImport
    }
    '/_authenticated/orders/$id/': {
      id: '/_authenticated/orders/$id/'
      path: '/'
      fullPath: '/orders/$id/'
      preLoaderRoute: typeof AuthenticatedOrdersIdIndexImport
      parentRoute: typeof AuthenticatedOrdersIdImport
    }
    '/_authenticated/trips/$id/': {
      id: '/_authenticated/trips/$id/'
      path: '/'
      fullPath: '/trips/$id/'
      preLoaderRoute: typeof AuthenticatedTripsIdIndexImport
      parentRoute: typeof AuthenticatedTripsIdImport
    }
    '/_authenticated/user/security/': {
      id: '/_authenticated/user/security/'
      path: '/user/security'
      fullPath: '/user/security'
      preLoaderRoute: typeof AuthenticatedUserSecurityIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/customers/corporate/$id/refill': {
      id: '/_authenticated/customers/corporate/$id/refill'
      path: '/refill'
      fullPath: '/customers/corporate/$id/refill'
      preLoaderRoute: typeof AuthenticatedCustomersCorporateIdRefillImport
      parentRoute: typeof AuthenticatedCustomersCorporateIdImport
    }
    '/_authenticated/user/security/_forms': {
      id: '/_authenticated/user/security/_forms'
      path: '/user/security'
      fullPath: '/user/security'
      preLoaderRoute: typeof AuthenticatedUserSecurityFormsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/user/security/_forms/_password-form': {
      id: '/_authenticated/user/security/_forms/_password-form'
      path: '/user/security'
      fullPath: '/user/security'
      preLoaderRoute: typeof AuthenticatedUserSecurityFormsPasswordFormImport
      parentRoute: typeof AuthenticatedUserSecurityFormsRoute
    }
    '/_authenticated/user/security/_forms/_pin-form': {
      id: '/_authenticated/user/security/_forms/_pin-form'
      path: ''
      fullPath: '/user/security'
      preLoaderRoute: typeof AuthenticatedUserSecurityFormsPinFormImport
      parentRoute: typeof AuthenticatedUserSecurityFormsImport
    }
    '/_authenticated/customers/corporate/$id/': {
      id: '/_authenticated/customers/corporate/$id/'
      path: '/'
      fullPath: '/customers/corporate/$id/'
      preLoaderRoute: typeof AuthenticatedCustomersCorporateIdIndexImport
      parentRoute: typeof AuthenticatedCustomersCorporateIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRoutesRouteChildren {
  AuthenticatedRoutesIdRoute: typeof AuthenticatedRoutesIdRoute
  AuthenticatedRoutesAddRoute: typeof AuthenticatedRoutesAddRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
}

const AuthenticatedRoutesRouteChildren: AuthenticatedRoutesRouteChildren = {
  AuthenticatedRoutesIdRoute: AuthenticatedRoutesIdRoute,
  AuthenticatedRoutesAddRoute: AuthenticatedRoutesAddRoute,
  AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
}

const AuthenticatedRoutesRouteWithChildren =
  AuthenticatedRoutesRoute._addFileChildren(AuthenticatedRoutesRouteChildren)

interface AuthenticatedSetupRouteChildren {
  AuthenticatedSetupAdditionalChargesRoute: typeof AuthenticatedSetupAdditionalChargesRoute
  AuthenticatedSetupConfigRoute: typeof AuthenticatedSetupConfigRoute
  AuthenticatedSetupItemCategoriesRoute: typeof AuthenticatedSetupItemCategoriesRoute
  AuthenticatedSetupItemTypesRoute: typeof AuthenticatedSetupItemTypesRoute
}

const AuthenticatedSetupRouteChildren: AuthenticatedSetupRouteChildren = {
  AuthenticatedSetupAdditionalChargesRoute:
    AuthenticatedSetupAdditionalChargesRoute,
  AuthenticatedSetupConfigRoute: AuthenticatedSetupConfigRoute,
  AuthenticatedSetupItemCategoriesRoute: AuthenticatedSetupItemCategoriesRoute,
  AuthenticatedSetupItemTypesRoute: AuthenticatedSetupItemTypesRoute,
}

const AuthenticatedSetupRouteWithChildren =
  AuthenticatedSetupRoute._addFileChildren(AuthenticatedSetupRouteChildren)

interface AuthenticatedShipmentsRouteChildren {
  AuthenticatedShipmentsIdRoute: typeof AuthenticatedShipmentsIdRoute
  AuthenticatedShipmentsNewRoute: typeof AuthenticatedShipmentsNewRoute
  AuthenticatedShipmentsIndexRoute: typeof AuthenticatedShipmentsIndexRoute
}

const AuthenticatedShipmentsRouteChildren: AuthenticatedShipmentsRouteChildren =
  {
    AuthenticatedShipmentsIdRoute: AuthenticatedShipmentsIdRoute,
    AuthenticatedShipmentsNewRoute: AuthenticatedShipmentsNewRoute,
    AuthenticatedShipmentsIndexRoute: AuthenticatedShipmentsIndexRoute,
  }

const AuthenticatedShipmentsRouteWithChildren =
  AuthenticatedShipmentsRoute._addFileChildren(
    AuthenticatedShipmentsRouteChildren,
  )

interface AuthenticatedTripsIdRouteChildren {
  AuthenticatedTripsIdEditRoute: typeof AuthenticatedTripsIdEditRoute
  AuthenticatedTripsIdIndexRoute: typeof AuthenticatedTripsIdIndexRoute
}

const AuthenticatedTripsIdRouteChildren: AuthenticatedTripsIdRouteChildren = {
  AuthenticatedTripsIdEditRoute: AuthenticatedTripsIdEditRoute,
  AuthenticatedTripsIdIndexRoute: AuthenticatedTripsIdIndexRoute,
}

const AuthenticatedTripsIdRouteWithChildren =
  AuthenticatedTripsIdRoute._addFileChildren(AuthenticatedTripsIdRouteChildren)

interface AuthenticatedTripsRouteChildren {
  AuthenticatedTripsIdRoute: typeof AuthenticatedTripsIdRouteWithChildren
  AuthenticatedTripsNewRoute: typeof AuthenticatedTripsNewRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedTripsRouteChildren: AuthenticatedTripsRouteChildren = {
  AuthenticatedTripsIdRoute: AuthenticatedTripsIdRouteWithChildren,
  AuthenticatedTripsNewRoute: AuthenticatedTripsNewRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedTripsRouteWithChildren =
  AuthenticatedTripsRoute._addFileChildren(AuthenticatedTripsRouteChildren)

interface AuthenticatedVehiclesRouteChildren {
  AuthenticatedVehiclesIdRoute: typeof AuthenticatedVehiclesIdRoute
  AuthenticatedVehiclesAddRoute: typeof AuthenticatedVehiclesAddRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
}

const AuthenticatedVehiclesRouteChildren: AuthenticatedVehiclesRouteChildren = {
  AuthenticatedVehiclesIdRoute: AuthenticatedVehiclesIdRoute,
  AuthenticatedVehiclesAddRoute: AuthenticatedVehiclesAddRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
}

const AuthenticatedVehiclesRouteWithChildren =
  AuthenticatedVehiclesRoute._addFileChildren(
    AuthenticatedVehiclesRouteChildren,
  )

interface AuthenticatedOrdersIdRouteChildren {
  AuthenticatedOrdersIdPaymentRoute: typeof AuthenticatedOrdersIdPaymentRoute
  AuthenticatedOrdersIdSummaryRoute: typeof AuthenticatedOrdersIdSummaryRoute
  AuthenticatedOrdersIdIndexRoute: typeof AuthenticatedOrdersIdIndexRoute
}

const AuthenticatedOrdersIdRouteChildren: AuthenticatedOrdersIdRouteChildren = {
  AuthenticatedOrdersIdPaymentRoute: AuthenticatedOrdersIdPaymentRoute,
  AuthenticatedOrdersIdSummaryRoute: AuthenticatedOrdersIdSummaryRoute,
  AuthenticatedOrdersIdIndexRoute: AuthenticatedOrdersIdIndexRoute,
}

const AuthenticatedOrdersIdRouteWithChildren =
  AuthenticatedOrdersIdRoute._addFileChildren(
    AuthenticatedOrdersIdRouteChildren,
  )

interface AuthenticatedCustomersCorporateIdRouteChildren {
  AuthenticatedCustomersCorporateIdRefillRoute: typeof AuthenticatedCustomersCorporateIdRefillRoute
  AuthenticatedCustomersCorporateIdIndexRoute: typeof AuthenticatedCustomersCorporateIdIndexRoute
}

const AuthenticatedCustomersCorporateIdRouteChildren: AuthenticatedCustomersCorporateIdRouteChildren =
  {
    AuthenticatedCustomersCorporateIdRefillRoute:
      AuthenticatedCustomersCorporateIdRefillRoute,
    AuthenticatedCustomersCorporateIdIndexRoute:
      AuthenticatedCustomersCorporateIdIndexRoute,
  }

const AuthenticatedCustomersCorporateIdRouteWithChildren =
  AuthenticatedCustomersCorporateIdRoute._addFileChildren(
    AuthenticatedCustomersCorporateIdRouteChildren,
  )

interface AuthenticatedUserSecurityFormsRouteChildren {
  AuthenticatedUserSecurityFormsPasswordFormRoute: typeof AuthenticatedUserSecurityFormsPasswordFormRoute
  AuthenticatedUserSecurityFormsPinFormRoute: typeof AuthenticatedUserSecurityFormsPinFormRoute
}

const AuthenticatedUserSecurityFormsRouteChildren: AuthenticatedUserSecurityFormsRouteChildren =
  {
    AuthenticatedUserSecurityFormsPasswordFormRoute:
      AuthenticatedUserSecurityFormsPasswordFormRoute,
    AuthenticatedUserSecurityFormsPinFormRoute:
      AuthenticatedUserSecurityFormsPinFormRoute,
  }

const AuthenticatedUserSecurityFormsRouteWithChildren =
  AuthenticatedUserSecurityFormsRoute._addFileChildren(
    AuthenticatedUserSecurityFormsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRouteWithChildren
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRouteWithChildren
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRouteWithChildren
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRouteWithChildren
  AuthenticatedCustomersAddRoute: typeof AuthenticatedCustomersAddRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRouteWithChildren
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
  AuthenticatedStaffAddRoute: typeof AuthenticatedStaffAddRoute
  AuthenticatedStationsAddRoute: typeof AuthenticatedStationsAddRoute
  AuthenticatedCustomersCorporateIdRoute: typeof AuthenticatedCustomersCorporateIdRouteWithChildren
  AuthenticatedCustomersCorporateAddRoute: typeof AuthenticatedCustomersCorporateAddRoute
  AuthenticatedUserSecurityIndexRoute: typeof AuthenticatedUserSecurityIndexRoute
  AuthenticatedUserSecurityFormsRoute: typeof AuthenticatedUserSecurityFormsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRouteWithChildren,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRouteWithChildren,
  AuthenticatedTripsRoute: AuthenticatedTripsRouteWithChildren,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRouteWithChildren,
  AuthenticatedCustomersAddRoute: AuthenticatedCustomersAddRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRouteWithChildren,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
  AuthenticatedStaffAddRoute: AuthenticatedStaffAddRoute,
  AuthenticatedStationsAddRoute: AuthenticatedStationsAddRoute,
  AuthenticatedCustomersCorporateIdRoute:
    AuthenticatedCustomersCorporateIdRouteWithChildren,
  AuthenticatedCustomersCorporateAddRoute:
    AuthenticatedCustomersCorporateAddRoute,
  AuthenticatedUserSecurityIndexRoute: AuthenticatedUserSecurityIndexRoute,
  AuthenticatedUserSecurityFormsRoute:
    AuthenticatedUserSecurityFormsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof unauthenticatedLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/setup': typeof AuthenticatedSetupRouteWithChildren
  '/shipments': typeof AuthenticatedShipmentsRouteWithChildren
  '/trips': typeof AuthenticatedTripsRouteWithChildren
  '/vehicles': typeof AuthenticatedVehiclesRouteWithChildren
  '/customers/add': typeof AuthenticatedCustomersAddRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/routes/$id': typeof AuthenticatedRoutesIdRoute
  '/routes/add': typeof AuthenticatedRoutesAddRoute
  '/setup/additional-charges': typeof AuthenticatedSetupAdditionalChargesRoute
  '/setup/config': typeof AuthenticatedSetupConfigRoute
  '/setup/item-categories': typeof AuthenticatedSetupItemCategoriesRoute
  '/setup/item-types': typeof AuthenticatedSetupItemTypesRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/staff/add': typeof AuthenticatedStaffAddRoute
  '/stations/add': typeof AuthenticatedStationsAddRoute
  '/trips/$id': typeof AuthenticatedTripsIdRouteWithChildren
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdRoute
  '/vehicles/add': typeof AuthenticatedVehiclesAddRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/shipments/': typeof AuthenticatedShipmentsIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/customers/corporate/$id': typeof AuthenticatedCustomersCorporateIdRouteWithChildren
  '/customers/corporate/add': typeof AuthenticatedCustomersCorporateAddRoute
  '/orders/$id/payment': typeof AuthenticatedOrdersIdPaymentRoute
  '/orders/$id/summary': typeof AuthenticatedOrdersIdSummaryRoute
  '/trips/$id/edit': typeof AuthenticatedTripsIdEditRoute
  '/orders/$id/': typeof AuthenticatedOrdersIdIndexRoute
  '/trips/$id/': typeof AuthenticatedTripsIdIndexRoute
  '/user/security': typeof AuthenticatedUserSecurityFormsPinFormRoute
  '/customers/corporate/$id/refill': typeof AuthenticatedCustomersCorporateIdRefillRoute
  '/customers/corporate/$id/': typeof AuthenticatedCustomersCorporateIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof unauthenticatedLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/setup': typeof AuthenticatedSetupRouteWithChildren
  '/customers/add': typeof AuthenticatedCustomersAddRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/routes/$id': typeof AuthenticatedRoutesIdRoute
  '/routes/add': typeof AuthenticatedRoutesAddRoute
  '/setup/additional-charges': typeof AuthenticatedSetupAdditionalChargesRoute
  '/setup/config': typeof AuthenticatedSetupConfigRoute
  '/setup/item-categories': typeof AuthenticatedSetupItemCategoriesRoute
  '/setup/item-types': typeof AuthenticatedSetupItemTypesRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/staff/add': typeof AuthenticatedStaffAddRoute
  '/stations/add': typeof AuthenticatedStationsAddRoute
  '/trips/new': typeof AuthenticatedTripsNewRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdRoute
  '/vehicles/add': typeof AuthenticatedVehiclesAddRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/shipments': typeof AuthenticatedShipmentsIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
  '/customers/corporate/add': typeof AuthenticatedCustomersCorporateAddRoute
  '/orders/$id/payment': typeof AuthenticatedOrdersIdPaymentRoute
  '/orders/$id/summary': typeof AuthenticatedOrdersIdSummaryRoute
  '/trips/$id/edit': typeof AuthenticatedTripsIdEditRoute
  '/orders/$id': typeof AuthenticatedOrdersIdIndexRoute
  '/trips/$id': typeof AuthenticatedTripsIdIndexRoute
  '/user/security': typeof AuthenticatedUserSecurityFormsPinFormRoute
  '/customers/corporate/$id/refill': typeof AuthenticatedCustomersCorporateIdRefillRoute
  '/customers/corporate/$id': typeof AuthenticatedCustomersCorporateIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof unauthenticatedLoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRouteWithChildren
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRouteWithChildren
  '/_authenticated/trips': typeof AuthenticatedTripsRouteWithChildren
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRouteWithChildren
  '/_authenticated/customers/add': typeof AuthenticatedCustomersAddRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/routes/$id': typeof AuthenticatedRoutesIdRoute
  '/_authenticated/routes/add': typeof AuthenticatedRoutesAddRoute
  '/_authenticated/setup/additional-charges': typeof AuthenticatedSetupAdditionalChargesRoute
  '/_authenticated/setup/config': typeof AuthenticatedSetupConfigRoute
  '/_authenticated/setup/item-categories': typeof AuthenticatedSetupItemCategoriesRoute
  '/_authenticated/setup/item-types': typeof AuthenticatedSetupItemTypesRoute
  '/_authenticated/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/_authenticated/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/_authenticated/staff/add': typeof AuthenticatedStaffAddRoute
  '/_authenticated/stations/add': typeof AuthenticatedStationsAddRoute
  '/_authenticated/trips/$id': typeof AuthenticatedTripsIdRouteWithChildren
  '/_authenticated/trips/new': typeof AuthenticatedTripsNewRoute
  '/_authenticated/vehicles/$id': typeof AuthenticatedVehiclesIdRoute
  '/_authenticated/vehicles/add': typeof AuthenticatedVehiclesAddRoute
  '/_authenticated/routes/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/shipments/': typeof AuthenticatedShipmentsIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/_authenticated/customers/corporate/$id': typeof AuthenticatedCustomersCorporateIdRouteWithChildren
  '/_authenticated/customers/corporate/add': typeof AuthenticatedCustomersCorporateAddRoute
  '/_authenticated/orders/$id/payment': typeof AuthenticatedOrdersIdPaymentRoute
  '/_authenticated/orders/$id/summary': typeof AuthenticatedOrdersIdSummaryRoute
  '/_authenticated/trips/$id/edit': typeof AuthenticatedTripsIdEditRoute
  '/_authenticated/orders/$id/': typeof AuthenticatedOrdersIdIndexRoute
  '/_authenticated/trips/$id/': typeof AuthenticatedTripsIdIndexRoute
  '/_authenticated/user/security/': typeof AuthenticatedUserSecurityIndexRoute
  '/_authenticated/customers/corporate/$id/refill': typeof AuthenticatedCustomersCorporateIdRefillRoute
  '/_authenticated/user/security/_forms': typeof AuthenticatedUserSecurityFormsRouteWithChildren
  '/_authenticated/user/security/_forms/_password-form': typeof AuthenticatedUserSecurityFormsPasswordFormRoute
  '/_authenticated/user/security/_forms/_pin-form': typeof AuthenticatedUserSecurityFormsPinFormRoute
  '/_authenticated/customers/corporate/$id/': typeof AuthenticatedCustomersCorporateIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/routes'
    | '/setup'
    | '/shipments'
    | '/trips'
    | '/vehicles'
    | '/customers/add'
    | '/orders/$id'
    | '/orders/new'
    | '/routes/$id'
    | '/routes/add'
    | '/setup/additional-charges'
    | '/setup/config'
    | '/setup/item-categories'
    | '/setup/item-types'
    | '/shipments/$id'
    | '/shipments/new'
    | '/staff/add'
    | '/stations/add'
    | '/trips/$id'
    | '/trips/new'
    | '/vehicles/$id'
    | '/vehicles/add'
    | '/routes/'
    | '/shipments/'
    | '/trips/'
    | '/vehicles/'
    | '/customers/corporate/$id'
    | '/customers/corporate/add'
    | '/orders/$id/payment'
    | '/orders/$id/summary'
    | '/trips/$id/edit'
    | '/orders/$id/'
    | '/trips/$id/'
    | '/user/security'
    | '/customers/corporate/$id/refill'
    | '/customers/corporate/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/setup'
    | '/customers/add'
    | '/orders/new'
    | '/routes/$id'
    | '/routes/add'
    | '/setup/additional-charges'
    | '/setup/config'
    | '/setup/item-categories'
    | '/setup/item-types'
    | '/shipments/$id'
    | '/shipments/new'
    | '/staff/add'
    | '/stations/add'
    | '/trips/new'
    | '/vehicles/$id'
    | '/vehicles/add'
    | '/routes'
    | '/shipments'
    | '/trips'
    | '/vehicles'
    | '/customers/corporate/add'
    | '/orders/$id/payment'
    | '/orders/$id/summary'
    | '/trips/$id/edit'
    | '/orders/$id'
    | '/trips/$id'
    | '/user/security'
    | '/customers/corporate/$id/refill'
    | '/customers/corporate/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/routes'
    | '/_authenticated/setup'
    | '/_authenticated/shipments'
    | '/_authenticated/trips'
    | '/_authenticated/vehicles'
    | '/_authenticated/customers/add'
    | '/_authenticated/orders/$id'
    | '/_authenticated/orders/new'
    | '/_authenticated/routes/$id'
    | '/_authenticated/routes/add'
    | '/_authenticated/setup/additional-charges'
    | '/_authenticated/setup/config'
    | '/_authenticated/setup/item-categories'
    | '/_authenticated/setup/item-types'
    | '/_authenticated/shipments/$id'
    | '/_authenticated/shipments/new'
    | '/_authenticated/staff/add'
    | '/_authenticated/stations/add'
    | '/_authenticated/trips/$id'
    | '/_authenticated/trips/new'
    | '/_authenticated/vehicles/$id'
    | '/_authenticated/vehicles/add'
    | '/_authenticated/routes/'
    | '/_authenticated/shipments/'
    | '/_authenticated/trips/'
    | '/_authenticated/vehicles/'
    | '/_authenticated/customers/corporate/$id'
    | '/_authenticated/customers/corporate/add'
    | '/_authenticated/orders/$id/payment'
    | '/_authenticated/orders/$id/summary'
    | '/_authenticated/trips/$id/edit'
    | '/_authenticated/orders/$id/'
    | '/_authenticated/trips/$id/'
    | '/_authenticated/user/security/'
    | '/_authenticated/customers/corporate/$id/refill'
    | '/_authenticated/user/security/_forms'
    | '/_authenticated/user/security/_forms/_password-form'
    | '/_authenticated/user/security/_forms/_pin-form'
    | '/_authenticated/customers/corporate/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  unauthenticatedLoginRoute: typeof unauthenticatedLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  unauthenticatedLoginRoute: unauthenticatedLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/routes",
        "/_authenticated/setup",
        "/_authenticated/shipments",
        "/_authenticated/trips",
        "/_authenticated/vehicles",
        "/_authenticated/customers/add",
        "/_authenticated/orders/$id",
        "/_authenticated/orders/new",
        "/_authenticated/staff/add",
        "/_authenticated/stations/add",
        "/_authenticated/customers/corporate/$id",
        "/_authenticated/customers/corporate/add",
        "/_authenticated/user/security/",
        "/_authenticated/user/security/_forms"
      ]
    },
    "/login": {
      "filePath": "(unauthenticated)/login.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/routes": {
      "filePath": "_authenticated/routes.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/routes/$id",
        "/_authenticated/routes/add",
        "/_authenticated/routes/"
      ]
    },
    "/_authenticated/setup": {
      "filePath": "_authenticated/setup.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/setup/additional-charges",
        "/_authenticated/setup/config",
        "/_authenticated/setup/item-categories",
        "/_authenticated/setup/item-types"
      ]
    },
    "/_authenticated/shipments": {
      "filePath": "_authenticated/shipments.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/shipments/$id",
        "/_authenticated/shipments/new",
        "/_authenticated/shipments/"
      ]
    },
    "/_authenticated/trips": {
      "filePath": "_authenticated/trips.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/trips/$id",
        "/_authenticated/trips/new",
        "/_authenticated/trips/"
      ]
    },
    "/_authenticated/vehicles": {
      "filePath": "_authenticated/vehicles.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/vehicles/$id",
        "/_authenticated/vehicles/add",
        "/_authenticated/vehicles/"
      ]
    },
    "/_authenticated/customers/add": {
      "filePath": "_authenticated/customers/add.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders/$id": {
      "filePath": "_authenticated/orders/$id.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/orders/$id/payment",
        "/_authenticated/orders/$id/summary",
        "/_authenticated/orders/$id/"
      ]
    },
    "/_authenticated/orders/new": {
      "filePath": "_authenticated/orders/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/routes/$id": {
      "filePath": "_authenticated/routes/$id.tsx",
      "parent": "/_authenticated/routes"
    },
    "/_authenticated/routes/add": {
      "filePath": "_authenticated/routes/add.tsx",
      "parent": "/_authenticated/routes"
    },
    "/_authenticated/setup/additional-charges": {
      "filePath": "_authenticated/setup/additional-charges.tsx",
      "parent": "/_authenticated/setup"
    },
    "/_authenticated/setup/config": {
      "filePath": "_authenticated/setup/config.tsx",
      "parent": "/_authenticated/setup"
    },
    "/_authenticated/setup/item-categories": {
      "filePath": "_authenticated/setup/item-categories.tsx",
      "parent": "/_authenticated/setup"
    },
    "/_authenticated/setup/item-types": {
      "filePath": "_authenticated/setup/item-types.tsx",
      "parent": "/_authenticated/setup"
    },
    "/_authenticated/shipments/$id": {
      "filePath": "_authenticated/shipments/$id.tsx",
      "parent": "/_authenticated/shipments"
    },
    "/_authenticated/shipments/new": {
      "filePath": "_authenticated/shipments/new.tsx",
      "parent": "/_authenticated/shipments"
    },
    "/_authenticated/staff/add": {
      "filePath": "_authenticated/staff/add.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/stations/add": {
      "filePath": "_authenticated/stations/add.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/trips/$id": {
      "filePath": "_authenticated/trips/$id.tsx",
      "parent": "/_authenticated/trips",
      "children": [
        "/_authenticated/trips/$id/edit",
        "/_authenticated/trips/$id/"
      ]
    },
    "/_authenticated/trips/new": {
      "filePath": "_authenticated/trips/new.tsx",
      "parent": "/_authenticated/trips"
    },
    "/_authenticated/vehicles/$id": {
      "filePath": "_authenticated/vehicles/$id.tsx",
      "parent": "/_authenticated/vehicles"
    },
    "/_authenticated/vehicles/add": {
      "filePath": "_authenticated/vehicles/add.tsx",
      "parent": "/_authenticated/vehicles"
    },
    "/_authenticated/routes/": {
      "filePath": "_authenticated/routes/index.tsx",
      "parent": "/_authenticated/routes"
    },
    "/_authenticated/shipments/": {
      "filePath": "_authenticated/shipments/index.tsx",
      "parent": "/_authenticated/shipments"
    },
    "/_authenticated/trips/": {
      "filePath": "_authenticated/trips/index.tsx",
      "parent": "/_authenticated/trips"
    },
    "/_authenticated/vehicles/": {
      "filePath": "_authenticated/vehicles/index.tsx",
      "parent": "/_authenticated/vehicles"
    },
    "/_authenticated/customers/corporate/$id": {
      "filePath": "_authenticated/customers/corporate/$id.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/customers/corporate/$id/refill",
        "/_authenticated/customers/corporate/$id/"
      ]
    },
    "/_authenticated/customers/corporate/add": {
      "filePath": "_authenticated/customers/corporate/add.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/orders/$id/payment": {
      "filePath": "_authenticated/orders/$id/payment.tsx",
      "parent": "/_authenticated/orders/$id"
    },
    "/_authenticated/orders/$id/summary": {
      "filePath": "_authenticated/orders/$id/summary.tsx",
      "parent": "/_authenticated/orders/$id"
    },
    "/_authenticated/trips/$id/edit": {
      "filePath": "_authenticated/trips/$id/edit.tsx",
      "parent": "/_authenticated/trips/$id"
    },
    "/_authenticated/orders/$id/": {
      "filePath": "_authenticated/orders/$id/index.tsx",
      "parent": "/_authenticated/orders/$id"
    },
    "/_authenticated/trips/$id/": {
      "filePath": "_authenticated/trips/$id/index.tsx",
      "parent": "/_authenticated/trips/$id"
    },
    "/_authenticated/user/security/": {
      "filePath": "_authenticated/user/security/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers/corporate/$id/refill": {
      "filePath": "_authenticated/customers/corporate/$id/refill.tsx",
      "parent": "/_authenticated/customers/corporate/$id"
    },
    "/_authenticated/user/security/_forms": {
      "filePath": "_authenticated/user/security/_forms",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/user/security/_forms/_password-form",
        "/_authenticated/user/security/_forms/_pin-form"
      ]
    },
    "/_authenticated/user/security/_forms/_password-form": {
      "filePath": "_authenticated/user/security/_forms/_password-form.tsx",
      "parent": "/_authenticated/user/security/_forms"
    },
    "/_authenticated/user/security/_forms/_pin-form": {
      "filePath": "_authenticated/user/security/_forms/_pin-form.tsx",
      "parent": "/_authenticated/user/security/_forms"
    },
    "/_authenticated/customers/corporate/$id/": {
      "filePath": "_authenticated/customers/corporate/$id/index.tsx",
      "parent": "/_authenticated/customers/corporate/$id"
    }
  }
}
ROUTE_MANIFEST_END */
